#theme: jekyll-theme-leap-day
remote_theme: pmarsceill/just-the-docs

# Enable or disable the site search
# Supports true (default) or false
search_enabled: true

# Site logo
logo: "https://github.com/ololx/ololx.github.io/blob/assets/ololx-logo-inverse.png"

# Aux links for the upper right navigation
aux_links:
  "View on GitHub":
    - "https://github.com/ololx/ololx.github.io"
