#theme: jekyll-theme-leap-day
remote_theme: pmarsceill/just-the-docs

# Enable or disable the site search
# Supports true (default) or false
search_enabled: true

# Enable or disable the search button that appears in the bottom right corner of every page
# Supports true or false (default)
search.button: true

# Maximum amount of previews per search result
# Default: 3
search.previews: 3

# Maximum amount of words to display before a matched word in the preview
# Default: 5
search.preview_words_before: 5

# Maximum amount of words to display after a matched word in the preview
# Default: 10
search.preview_words_after: 10

# Set the search token separator
# Default: /[\s\-/]+/
# Example: enable support for hyphenated search words
search.tokenizer_separator: /[\s/]+/

# Display the relative url in search results
# Supports true (default) or false
search.rel_url: true

# Site logo
logo: "https://github.com/ololx/ololx.github.io/blob/assets/ololx-logo-inverse.png"

# Aux links for the upper right navigation
aux_links:
  "View on GitHub":
    - "https://github.com/ololx/ololx.github.io"
